/**
 * FILE OBJECTIVE:
 * - Compile/import test for worker/metrics-server.ts
 *
 * LINKED UNIT TEST:
 * - tests/unit/worker/metrics-server.ts.test.ts
 *
 * EDIT LOG:
 * - 2026-01-02T17:08:41.704Z | copilot | autogenerated conversion
 */

import path from 'path'

describe('worker/metrics-server.ts', () => {
  test('module imports and basic exports', () => {
    const p = path.join(process.cwd(), 'worker/metrics-server.ts')
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const mod = require(p)
    if (!mod) throw new Error('module not defined')
  })
})
