import { NextResponse } from 'next/server'
import { getServerSessionForHandlers } from '@/lib/session'
import { getRedis } from '@/lib/redis'
import { prisma } from '@/lib/prisma'
import { logger } from '@/lib/logger'

export const dynamic = 'force-dynamic'

/**
 * POST /api/parent/link-child
 * Body: { inviteToken: string }
 *
 * Validates the Redis invite token generated by POST /api/student/invite-parent,
 * creates (or reactivates) the ParentStudent link, promotes caller to role=parent,
 * and burns the token (single-use).
 *
 * Returns: { linked: true, studentName }
 */
export async function POST(req: Request) {
  const start = Date.now()
  const session = await getServerSessionForHandlers()
  const parentId = (session?.user as { id?: string })?.id
  if (!parentId) {
    const res = NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    logger.logAPI(req, res, { className: 'LinkChildAPI', methodName: 'POST' }, start)
    return res
  }

  let body: unknown
  try {
    body = await req.json()
  } catch {
    const res = NextResponse.json({ error: 'Invalid JSON' }, { status: 400 })
    logger.logAPI(req, res, { className: 'LinkChildAPI', methodName: 'POST' }, start)
    return res
  }

  const inviteToken = typeof (body as any)?.inviteToken === 'string'
    ? (body as any).inviteToken.trim()
    : ''
  if (!inviteToken) {
    const res = NextResponse.json({ error: 'inviteToken required' }, { status: 400 })
    logger.logAPI(req, res, { className: 'LinkChildAPI', methodName: 'POST' }, start)
    return res
  }

  const redis = getRedis()
  if (!redis) {
    const res = NextResponse.json({ error: 'Service temporarily unavailable' }, { status: 503 })
    logger.logAPI(req, res, { className: 'LinkChildAPI', methodName: 'POST' }, start)
    return res
  }

  const key = `parent_invite:${inviteToken}`
  const studentId = await redis.get(key)

  if (!studentId) {
    const res = NextResponse.json({ error: 'Invite link is invalid or has expired' }, { status: 404 })
    logger.logAPI(req, res, { className: 'LinkChildAPI', methodName: 'POST' }, start)
    return res
  }

  if (studentId === parentId) {
    const res = NextResponse.json({ error: 'Cannot link to yourself' }, { status: 400 })
    logger.logAPI(req, res, { className: 'LinkChildAPI', methodName: 'POST' }, start)
    return res
  }

  // Burn the token (single-use)
  await redis.del(key)

  // Upsert ParentStudent row
  const existing = await prisma.parentStudent.findUnique({
    where: { parentId_studentId: { parentId, studentId } },
    select: { id: true, status: true },
  })

  if (existing?.status === 'active') {
    // Already linked -- idempotent
  } else if (existing?.status === 'revoked') {
    await prisma.parentStudent.update({
      where: { id: existing.id },
      data: { status: 'active' },
    })
  } else if (!existing) {
    await prisma.parentStudent.create({
      data: { parentId, studentId, status: 'active' },
    })
  }

  // Promote caller to parent role if they're still a regular user
  const parentUser = await prisma.user.findUnique({
    where: { id: parentId },
    select: { role: true },
  })
  if (parentUser?.role === 'user') {
    await prisma.user.update({ where: { id: parentId }, data: { role: 'parent' } })
  }

  // Fetch student name for response
  const student = await prisma.user.findUnique({
    where: { id: studentId },
    select: { name: true },
  })

  // Audit log (non-fatal)
  prisma.auditLog.create({
    data: {
      adminId: parentId,
      targetEntity: 'User',
      targetId: studentId,
      action: null,
      details: { legacyAction: 'parent_link_student', parentId, method: 'redis_invite_token' },
    },
  }).catch(() => {})

  const res = NextResponse.json(
    { linked: true, studentName: student?.name ?? 'Student' },
    { status: 200 },
  )
  logger.logAPI(req, res, { className: 'LinkChildAPI', methodName: 'POST' }, start)
  return res
}
