/**
 * FILE OBJECTIVE:
 * - Endpoint to consume a student-generated invite token and link a parent
 *   account to the student. Promotes the caller to `role=parent` when needed.
 *
 * LINKED UNIT TEST:
 * - tests/unit/api/parent-link-child.spec.ts
 *
 * COPILOT INSTRUCTIONS FOLLOWED:
 * - .github/copilot-instructions.md
 * - /docs/COPILOT_GUARDRAILS.md
 *
 * EDIT LOG:
 * - 2026-04-09T00:00:00Z | copilot | enforce max-3 children server-side; send welcome notification
 * - 2026-04-12T12:00:00Z | copilot | use FAMILY_MAX_CHILDREN constant from billing constants
 * - 2026-05-13T00:00:00Z | copilot | emit parent linked analytics when child invite is consumed
 */

import { NextResponse } from 'next/server'
import { getServerSessionForHandlers } from '@/lib/session'
import { getRedis } from '@/lib/redis'
import { prisma } from '@/lib/prisma'
import { logger } from '@/lib/logger'
import { sendMailSafe } from '@/lib/mailer'
import { sendSms } from '@/lib/sms'
import { FAMILY_MAX_CHILDREN } from '@/app/api/billing/constants'
import { emitServerAnalyticsEvent } from '@/lib/analytics/server'
import { ANALYTICS_EVENTS } from '@/lib/analytics/events'

export const dynamic = 'force-dynamic'

/**
 * POST /api/parent/link-child
 * Body: { inviteToken: string }
 *
 * Validates the Redis invite token generated by POST /api/student/invite-parent,
 * creates (or reactivates) the ParentStudent link, promotes caller to role=parent,
 * and burns the token (single-use).
 *
 * Returns: { linked: true, studentName }
 */
export async function POST(req: Request) {
  const start = Date.now()
  const session = await getServerSessionForHandlers()
  const parentId = (session?.user as { id?: string })?.id
  if (!parentId) {
    const res = NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    logger.logAPI(req, res, { className: 'LinkChildAPI', methodName: 'POST' }, start)
    return res
  }

  let body: unknown
  try {
    body = await req.json()
  } catch {
    const res = NextResponse.json({ error: 'Invalid JSON' }, { status: 400 })
    logger.logAPI(req, res, { className: 'LinkChildAPI', methodName: 'POST' }, start)
    return res
  }

  const inviteToken = typeof (body as any)?.inviteToken === 'string'
    ? (body as any).inviteToken.trim()
    : ''
  if (!inviteToken) {
    const res = NextResponse.json({ error: 'inviteToken required' }, { status: 400 })
    logger.logAPI(req, res, { className: 'LinkChildAPI', methodName: 'POST' }, start)
    return res
  }

  const redis = getRedis()
  if (!redis) {
    const res = NextResponse.json({ error: 'Service temporarily unavailable' }, { status: 503 })
    logger.logAPI(req, res, { className: 'LinkChildAPI', methodName: 'POST' }, start)
    return res
  }

  const key = `parent_invite:${inviteToken}`
  const studentId = await redis.get(key)

  if (!studentId) {
    const res = NextResponse.json({ error: 'Invite link is invalid or has expired' }, { status: 404 })
    logger.logAPI(req, res, { className: 'LinkChildAPI', methodName: 'POST' }, start)
    return res
  }

  if (studentId === parentId) {
    const res = NextResponse.json({ error: 'Cannot link to yourself' }, { status: 400 })
    logger.logAPI(req, res, { className: 'LinkChildAPI', methodName: 'POST' }, start)
    return res
  }

  // Burn the token (single-use)
  await redis.del(key)

  // Upsert ParentStudent row
  const existing = await prisma.parentStudent.findUnique({
    where: { parentId_studentId: { parentId, studentId } },
    select: { id: true, status: true },
  })

  // Enforce server-side cap: max FAMILY_MAX_CHILDREN active child links per parent
  // If this link is already active, allow; otherwise, count other active links
  const activeCount = await prisma.parentStudent.count({
    where: {
      parentId,
      studentId: { not: studentId },
      status: 'active',
    },
  })
  if (!existing || existing.status === 'revoked') {
    if (activeCount >= FAMILY_MAX_CHILDREN) {
      const res = NextResponse.json({ error: `Parent already has maximum linked children (${FAMILY_MAX_CHILDREN})` }, { status: 409 })
      logger.logAPI(req, res, { className: 'LinkChildAPI', methodName: 'POST' }, start)
      return res
    }
  }

  if (existing?.status === 'active') {
    // Already linked -- idempotent
  } else if (existing?.status === 'revoked') {
    await prisma.parentStudent.update({
      where: { id: existing.id },
      data: { status: 'active' },
    })
  } else if (!existing) {
    await prisma.parentStudent.create({
      data: { parentId, studentId, status: 'active' },
    })
  }

  void emitServerAnalyticsEvent(
    {
      eventType: ANALYTICS_EVENTS.PARENT.LINKED,
      userId: parentId,
      metadata: {
        parentId,
        studentId,
        reactivated: existing?.status === 'revoked',
      },
    },
    'parent.link-child',
  )

  // Promote caller to parent role if they're still a regular user
  const parentUser = await prisma.user.findUnique({
    where: { id: parentId },
    select: { role: true, email: true, phone: true, name: true },
  })
  let promoted = false
  if (parentUser?.role === 'user') {
    await prisma.user.update({ where: { id: parentId }, data: { role: 'parent' } })
    promoted = true
  }

  if (promoted) {
    logger.info('Promoted user to parent role', { className: 'LinkChildAPI', parentId })
  }

  // Fetch student name for response
  const student = await prisma.user.findUnique({
    where: { id: studentId },
    select: { name: true },
  })

  // Audit log (non-fatal) -- best-effort, log failures
  prisma.auditLog.create({
    data: {
      adminId: parentId,
      targetEntity: 'User',
      targetId: studentId,
      action: null,
      details: { legacyAction: 'parent_link_student', parentId, method: 'redis_invite_token' },
    },
  }).catch((err) => logger.debug('auditLog.create failed', { className: 'LinkChildAPI', error: String(err) }))

  // Send welcome/confirmation notifications to the parent (best-effort)
  try {
    const parentEmail = parentUser?.email
    const parentPhone = parentUser?.phone
    const parentName = parentUser?.name ?? 'Parent'
    const studentName = student?.name ?? 'your child'
    if (parentEmail) {
      await sendMailSafe({
        to: parentEmail,
        subject: `Welcome -- linked to ${studentName}`,
        html: `<p>Hi ${parentName},</p><p>You are now linked to ${studentName} on Spinzy.</p><p>If this wasn't you, contact support.</p>`,
      })
    }
    if (parentPhone) {
      await sendSms(parentPhone, `You're now linked to ${studentName} on Spinzy Academy.`)
    }
  } catch (err) {
    // best-effort only
    logger.error('[link-child] welcome notification suppressed', { error: err })
  }

  const res = NextResponse.json(
    { linked: true, studentName: student?.name ?? 'Student' },
    { status: 200 },
  )
  logger.logAPI(req, res, { className: 'LinkChildAPI', methodName: 'POST' }, start)
  return res
}
