/**
 * FILE OBJECTIVE:
 * - Compile/import test for types/next-shims.d.ts
 *
 * LINKED UNIT TEST:
 * - tests/unit/types/next-shims.d.ts.test.ts
 *
 * EDIT LOG:
 * - 2026-01-02T17:08:41.684Z | copilot | autogenerated conversion
 */

import path from 'path'

describe('types/next-shims.d.ts', () => {
  test('module imports and basic exports', () => {
    const p = path.join(process.cwd(), 'types/next-shims.d.ts')
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const mod = require(p)
    if (!mod) throw new Error('module not defined')
  })
})
